//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    

    public partial class Table
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Wypelnij wymagane pole!")]
        [RegularExpression(@"^[a-zA-Z_]{2,20}$", ErrorMessage = "Niepoprawnie imie.")]
        public string Imie { get; set; }
        [Required(ErrorMessage = "Wypelnij wymagane pole!")]
        [RegularExpression(@"^[a-zA-Z_]{2,25}$", ErrorMessage = "Niepoprawnie nazwisko.")]
        public string Naziwsko { get; set; }
        [Required(ErrorMessage = "Wypelnij wymagane pole!")]
        [RegularExpression(@"^[a-zA-Z_]{2,30}$", ErrorMessage = "Niepoprawna miejscowosc.")]
        public string Miejscowosc { get; set; }
        public string Ulica { get; set; }
        [DisplayName("Nr. domu/mieszkania")]
        public string Nr_domu { get; set; }
        [Required(ErrorMessage = "Wypelnij wymagane pole!")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\d{9}$", ErrorMessage = "Zly format numeru telefonu.")]
        public string Telefon { get; set; }
    }
}
